apiVersion: devops.my.domain/v1
kind: MicroService
metadata:
  name: microservice-sample
spec:
  # Add fields here
  size: 2
  image: nginx:1.7.9
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
